<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <AnalysisLevel>latest</AnalysisLevel>
  </PropertyGroup>

  <ItemGroup Condition="'$(MSBuildProjectName)' == 'SingPlus.Kernel'">
    <ProjectReference Include="$(MSBuildThisFileDirectory)sdk\SingPlus.Analyzers\SingPlus.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="$(MSBuildThisFileDirectory)sdk\SingPlus.Generators\SingPlus.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
