<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <AssemblyName>SingNext.Boot.Capsule</AssemblyName>
    <RootNamespace>SingNext.Boot.Capsule</RootNamespace>
    <SingCapSecurityProfile>BootCapsule</SingCapSecurityProfile>
    <SingPlusMemoryProfile>KernelNoHeap</SingPlusMemoryProfile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SingNext.Boot.Core/SingNext.Boot.Core.csproj" />
    <ProjectReference Include="../../../Platform/SingPlus.Platform.HybridCpu.Boot/SingPlus.Platform.HybridCpu.Boot.csproj" />
    <ProjectReference Include="../../../../tools/HybridCpu_ExecutableAdapter/Boot.Contracts/HybridCpu.Boot.Contracts.csproj" />
  </ItemGroup>
</Project>
