<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\contracts\SingPlus.Contracts\SingPlus.Contracts.csproj" />
    <ProjectReference Include="..\..\Platform\SingPlus.Platform.Abstractions\SingPlus.Platform.Abstractions.csproj" />
    <ProjectReference Include="..\..\Sip\SingPlus.Sip\SingPlus.Sip.csproj" />
    <ProjectReference Include="..\..\..\tools\HybridCpu_ExecutableAdapter\Boot.Contracts\HybridCpu.Boot.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HybridCPU.ExternalRuntime.Contracts" Version="[1.14.0]" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <RestoreLockedMode Condition="'$(CI)' == 'true'">true</RestoreLockedMode>
  </PropertyGroup>

</Project>
