<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\contracts\SingPlus.Contracts\SingPlus.Contracts.csproj" />
    <ProjectReference Include="..\..\Platform\SingPlus.Platform.Abstractions\SingPlus.Platform.Abstractions.csproj" />
    <ProjectReference Include="..\..\Sip\SingPlus.Sip\SingPlus.Sip.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
