<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <StripSymbols>true</StripSymbols>
    <SingCapSecurityProfile>ManagedCap</SingCapSecurityProfile>
    <SingPlusEnableAdmission>true</SingPlusEnableAdmission>
    <SingPlusMemoryProfile>ManagedCap</SingPlusMemoryProfile>
    <SingPlusAdmissionRoot>SingCap.ManagedCap.NativeAotFixture.Program::Main</SingPlusAdmissionRoot>
  </PropertyGroup>
</Project>
