<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot Condition="'$(SingPlusNativeAotQualification)' == 'true'">true</PublishAot>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SingPlus.Admission/SingPlus.Admission.csproj" />
  </ItemGroup>
</Project>
